### ISSUE TITLE
implement error handling 

### ISSUE THREAD

**Issue by ncstefan** [ncstefan/alexa-commute-info#14]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-voice-interface-and-user-experience-testing#error-handling

**Comment by ghost** [comment]
nameIntent cannot have error handling if no name is said because Alexa will always try to record and detect a name

**Comment by ghost** [comment]
yes/no error handling: make Alexa repeat the question if no valid answer is given
