### ISSUE TITLE
Repurpose NameIntent() for name not recognized in TrafficIntent()

### ISSUE THREAD

**Issue by ncstefan** [ncstefan/alexa-commute-info#5]

**Comment by ghost** [comment]
Workflow:
1. Verify user and send card if not found.
2. Play home address if found. Play list of names. Ask name by saying "my name is:" <blah>
3. Modify NameIntent() to trigger on "my name". Confirm name: "I heard <name>. Is that correct?"
4. Read traffic duration on YesIntent().
5. Ask name again on NoIntent().
