### ISSUE TITLE
certification requirements from amz

### ISSUE THREAD

**Issue by ghost** [ncstefan/alexa-commute-info#9]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-submission-checklist

**Comment by ncstefan** [comment]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-submission-checklist

**Comment by ncstefan** [comment]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-submission-checklist

**Comment by ncstefan** [comment]
- [ ] Submitting an Alexa app for certification  
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/publishing-an-alexa-skill

**Certification requirements for Custom Skills**
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-submission-checklist


- [x] Security Requirements
  - Verify that the request is intended for your service  
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/handling-requests-sent-by-alexa

- [x] Policy Requirements:
  - Misuses customer personally identifiable information or sensitive personal information. 
  - Collects personal information from end users, and you fail to do all of the following: (i) provide notice of that data collection to end users in your skill’s detail page, (ii) use the information in a way that end users have consented to, and (iii) ensure that your collection and use of that information complies with your privacy notice and all applicable laws. Prior to submitting a skill that collects personal information from end users, you are required to supply a privacy policy that will be displayed to end users on your skill’s detail page in the Alexa App.

- [x] Functional Testing
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-functional-testing

- [x] User Experience Testing
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-voice-interface-and-user-experience-testing  
  
- [x] Publishing the App as a Skill  
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/publishing-an-alexa-skill

- [x] Terms and Conditions  
  
- [x] Submission Checklist:
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-submission-checklist

**Comment by DanyStefan** [comment]
not authorized to delete custom slot types
